# Change these first
owner: kerberos-io # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Public site
    url: https://kerberos.io
  - name: Documentation
    url: https://doc.kerberos.io
  - name: Agent Demo
    url: https://demo.kerberos.io
  - name: Hub
    url: https://app.kerberos.io

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.kerberos.io
  # baseUrl: /your-repo-name
  logoUrl: https://doc.kerberos.io/images/kerberos-logo.svg
  name: Kerberos.io
  introTitle: "Kerberos.io"
  introMessage: A scalable video analytics and video management platform, build on top of Docker and Kubernetes, for everyone and everywhere.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
